### ISSUE TITLE
Usage Guide

### ISSUE THREAD

**Issue by knownasilya** [erobit/meteor-accounts-ui-bootstrap-dropdown#1]
How exactly do we go about using this plugin instead of the default Accounts UI plugin? Is it just a drag and drop into the local packages in static_cacheable? Or do I also have to do meteor add meteor-accounts-ui-bootstrap-dropdown?

**Comment by erobit** [comment]
You should use meteorite (meteor version/package manager)
http://oortcloud.github.com/meteorite/

I've published the package to atmosphere, here's how to get started
https://atmosphere.meteor.com/wtf/app

mrt add accounts-ui-bootstrap-dropdown
