### ISSUE TITLE
Form does not properly respond to forbidClientAccountCreation

### ISSUE THREAD

**Issue by jasonsocha** [erobit/meteor-accounts-ui-bootstrap-dropdown#10]
According to the docs:

**forbidClientAccountCreation** Boolean
Calls to createUser from the client will be rejected. In addition, if you are using accounts-ui, the "Create account" link will not be available.

The second part of this doesn't take effect if using the accounts-ui-bootstrap-dropdown package.  The Create Account link still appears and the sign-up form is still presented.

Attempts to use the sign-up form fail, as they should.  But the button & form should not appear at all if the forbidClientAccountCreation flag is set.

**Comment by erobit** [comment]
Ah yes. I haven't kept parity with the updates that have been made to the original accounts-ui-unstyled package.

For example...
https://github.com/meteor/meteor/commit/ae68aa22e6e9ef9ad015d7a5e5c60c3c82f8f62a

I'll see what I can do this weekend to regain feature parity with accounts-ui-unstyled

**Comment by erobit** [comment]
We now have feature parity with accounts-ui-unstyled 0.6.5. This should no longer be an issue.
