### ISSUE TITLE
Dependency on bootstrap core package

### ISSUE THREAD

**Issue by mdede** [erobit/meteor-accounts-ui-bootstrap-dropdown#14]
Hi Eric,
I'm using you package with non-core bootstrap package (bootstrap-less). But your package depends on the core package. The result is that bundled .css file contains two bootstraps: the core one included via dependency from your package.js and wanted bootstrap-less package. And some browsers are indeed confused (IE specially). Could you please remove this dependency?
Thanks, Milos.

**Comment by jamesdwilson** [comment]
+1

**Comment by erobit** [comment]
Fixed with latest release. You now have to manually install your bootstrap package. Readme updated.
