### ISSUE TITLE
`accounts-urls` package no longer exists in 0.6.5

### ISSUE THREAD

**Issue by tmeasday** [erobit/meteor-accounts-ui-bootstrap-dropdown#15]
I think you get it for free with accounts-base.

See:

https://github.com/DiscoverMeteor/book/issues/68

**Comment by michaelbishop** [comment]
accounts-url has been rolled into accounts-base:

David Glasser glasser@meteor.com via googlegroups.com 
Aug 12 (3 days ago)
to meteor-core 

> The accounts-url internal package was rolled into accounts-base and
> doesn't exist any more.

OK, so I removed the package requirement, but then got this error
`Uncaught ReferenceError: Handlebars is not defined`

I fiddled with api.use and api.imply and got it working, but it said no services were configured. At this point it appears that the package API is in such flux that I'm going back to the previous version.

If anyone is interested in how to downgrade I used this post by David Glasser:

David Glasser glasser@meteor.com via googlegroups.com 
3:04 PM (22 hours ago)
to meteor-talk 

> Meteor 0.6.5 changes the package API to explicitly require them to
> declare their exports instead of forcing them to pollute the global
> namespace.
> 
> This means that if you're using Atmosphere packages that haven't yet
> updated to the new interface, you might discover that your app no
> longer works, and want to continue using 0.6.4.1 until all your
> favorite packages are updated.
> 
> The way to downgrade is:
> 
>  $ meteor update --release 0.6.4.1
> 
> ... but that won't actually undo the other change that updating your
> app to 0.6.5 did.  So you'll also want to edit your ".meteor/packages"
> file and remove the line "standard-app-packages".
> 
> (As part of our roadmapped work on packaging, we want to officially
> support Atmosphere packages and make them work even when underlying
> APIs change, but we're not there yet!)
> 
> --dave
> 
> (By the way, package authors, if you want to make your package
> temporarily work on 0.6.4 and 0.6.5, just put `if (api.export)` before
> the call to `api.export`!)
