### ISSUE TITLE
error: no such package: 'accounts-urls'

### ISSUE THREAD

**Issue by jamesdwilson** [erobit/meteor-accounts-ui-bootstrap-dropdown#18]
David Glasser said:

The accounts-url internal package was rolled into accounts-base and
doesn't exist any more.

---

=> Errors while scanning packages:

While building package `accounts-ui-bootstrap-dropdown`:
error: no such package: 'accounts-urls'
james@eros ~/projects/meteor-skeleton $ 
james@eros ~/projects/meteor-skeleton $ 
james@eros ~/projects/meteor-skeleton $ meteor add accounts-urls
=> Errors while scanning packages:

While building package `accounts-ui-bootstrap-dropdown`:
error: no such package: 'accounts-urls'
james@eros ~/projects/meteor-skeleton $ mrt add accounts-urls

/usr/lib/node_modules/meteorite/lib/project.js:224
          throw("Package named " + pkgName + " doesn't exist in your meteor in
                                           ^
Package named accounts-urls doesn't exist in your meteor installation, smart.json, or on atmosphere
james@eros ~/projects/meteor-skeleton $

**Comment by erobit** [comment]
Should no longer be an issue - We now have parity with meteor 0.6.5 accounts-ui-unstyled and package.js has been updated - Tx tmeasday.
