### ISSUE TITLE
Deprecate in favor of mangasocial's fork?

### ISSUE THREAD

**Issue by dandv** [erobit/meteor-accounts-ui-bootstrap-dropdown#28]
Not sure if this package is still being maintained. If the author has moved on, maybe it would help to direct users to one of the actively maintained forks, like [mangasocial](https://github.com/mangasocial/meteor-accounts-ui-bootstrap-3)'s?

**Comment by dandv** [comment]
@erobit: what was the resolution on this?

**Comment by erobit** [comment]
Hi @dandv, 

The package is still being maintained. I have not received any pull requests or communication from mangasocial so it is disingenuous to simply deprecate my contribution of this package in favour of the fork as you suggest. If there are outstanding issues or enhancements that you would like to see fixed / completed, please contribute to the issues list and the comments and we can resolve them.

**Comment by dandv** [comment]
Thanks Eric. Wasn't saying the package _should_ be deprecated, just wondering if it was still being maintained. Good to see it is.
