### ISSUE TITLE
Error when updated meteor to 0.8

### ISSUE THREAD

**Issue by joshux** [erobit/meteor-accounts-ui-bootstrap-dropdown#30]
This is the error message:

While building package `accounts-ui-bootstrap-dropdown`:
error: no such package: 'spark'
login_buttons.html:89: Only certain elements like BR, HR, IMG, etc. (and foreign elements like SVG) are allowed to self-close
...n-buttons-padding" />   {{/unless}}
                        ^

**Comment by stared** [comment]
I had the same error, but when run `mrt update` I got:

```
While building package `accounts-ui-bootstrap-dropdown`:
error: no such package: 'spark'
```

(without the self-close part).

**Comment by sferoze** [comment]
I am having the same error when running 0.8.0. Running with blaze-rc1 works fine though. 

```
=> Errors while scanning packages:

While building package `accounts-ui-bootstrap-dropdown`:
error: no such package: 'spark'
Ferozes-iMac:microscope Feroze$ mrt add spark
```

**Comment by ccbcqbz** [comment]
having exactly the same issue. still no solution yet?

**Comment by erobit** [comment]
I'm looking into the issue. I'll be committing an updated package soon.

**Comment by sferoze** [comment]
I am trying to add accounts-ui-bootstrap-dropdown package and I get this error:

```
ERROR: 1 Command failed: error: pathspec 'v0.8.1' did not match any file(s) known to git
```

Is this because a tag has been created but not been pushed yet?

**Comment by sferoze** [comment]
I notice a 0.8.2 tag, but it hasn't been labeled as the latest release. Does updating or adding this package work now? When I tried earlier today I kept getting that error which would break my app. Then I had to rollback to tag v0.8.0 because I kept getting the error I left in the comment above.

**Comment by erobit** [comment]
I believe if you mrt update, everything should be in order.

**Comment by sferoze** [comment]
I just updated and it worked out, now I am on 0.8.0 without any issues! Thanks a bunch!

**Comment by stared** [comment]
Now it works, thx @erobit !

**Comment by ccbcqbz** [comment]
@erobit , cool. It's working now! v0.8.3
Tks a lot!
