### ISSUE TITLE
no such package error Meteor 0.8.1.2

### ISSUE THREAD

**Issue by ghost** [erobit/meteor-accounts-ui-bootstrap-dropdown#33]
Hello.

I'm having an issue when building, I have Meteor 0.8.1.2 and the error is:

While building the application:
error: no such package: 'accounts-ui-bootstrap-dropdown'

I have tried mrt update etc. Cheers.

UPDATE: doing an mrt remove ... then adding it again and the app runs, however I get an error to do with multiple templates having the same name. I'll keep playing.

**Comment by ghost** [comment]
Don't know if you solve the issue or not. 

Check your subdirectories in the project. I had the same error when I accidentally run `mrt add <packages>` under clients subdirectory. And it added extra packages folder in there, which caused this error.

**Comment by erobit** [comment]
Last comment should solve the issue.
