### ISSUE TITLE
Please update tag/version to the latest commit

### ISSUE THREAD

**Issue by dburles** [erobit/meteor-accounts-ui-bootstrap-dropdown#6]
mrt add is referencing the earlier commit that's referenced in tag 0.1.0

**Comment by erobit** [comment]
I keep getting an error when trying to release / publish.

/usr/local/lib/node_modules/meteorite/lib/atmosphere.js:44
        throw "Tag " + versionName + " doesn't exist in repository, please add
                                   ^
Tag vundefined doesn't exist in repository, please add!

**Comment by erobit** [comment]
I'll see if I can hook up with tmeasday to resolve this issue. I've always found the tagging mrt update process a little wonky - I remember encountering an issue the first time I published the module to atmosphere as well.

**Comment by tmeasday** [comment]
@erobit that's odd. How are you publishing?
