### ISSUE TITLE
Accounts.registerLoginHandler no longer works.

### ISSUE THREAD

**Issue by mizzao** [erobit/meteor-accounts-ui-bootstrap-dropdown#9]
When switching from accounts-ui to this, my custom login handler doesn't work anymore. i.e.:

`Accounts.registerLoginHandler( function ...)` in a server-side file is busted. I assumed that this would be the same as accounts-ui except for styling, but has this functionality changed?

**Comment by erobit** [comment]
Hi mizzao,

I'm guessing its due to changes with accounts-ui that haven't been merged into my repo. I'll see what I can do this weekend to regain feature parity with the original accounts-ui-unstyled package and re-publish to atmosphere.

**Comment by mizzao** [comment]
Maybe consider depending on accounts-ui-unstyled and just replace the templates while using the JS? Seems like it could save you some work compared to replicating the functionality each time.

**Comment by erobit** [comment]
mizzao, we can't use the stock .js files from accounts-ui-unstyled unfortunately as they have been modified to support bootstrap ui / workflow. I'll do my best to keep feature parity in the future. We have feature parity with 0.6.5 so I'll close this issue.
